// Data preset untuk Hiragana dan Katakana
const presetData = {
  hiraganaBasic: {
    questions: [
      "あ",
      "い",
      "う",
      "え",
      "お",
      "か",
      "き",
      "く",
      "け",
      "こ",
      "さ",
      "し",
      "す",
      "せ",
      "そ",
      "た",
      "ち",
      "つ",
      "て",
      "と",
      "な",
      "に",
      "ぬ",
      "ね",
      "の",
      "は",
      "ひ",
      "ふ",
      "へ",
      "ほ",
      "ま",
      "み",
      "む",
      "め",
      "も",
      "や",
      "ゆ",
      "よ",
      "ら",
      "り",
      "る",
      "れ",
      "ろ",
      "わ",
      "を",
      "ん",
    ],
    answers: [
      "a",
      "i",
      "u",
      "e",
      "o",
      "ka",
      "ki",
      "ku",
      "ke",
      "ko",
      "sa",
      "shi",
      "su",
      "se",
      "so",
      "ta",
      "chi",
      "tsu",
      "te",
      "to",
      "na",
      "ni",
      "nu",
      "ne",
      "no",
      "ha",
      "hi",
      "fu",
      "he",
      "ho",
      "ma",
      "mi",
      "mu",
      "me",
      "mo",
      "ya",
      "yu",
      "yo",
      "ra",
      "ri",
      "ru",
      "re",
      "ro",
      "wa",
      "wo",
      "n",
    ],
  },
  hiraganaTenten: {
    questions: [
      "が",
      "ぎ",
      "ぐ",
      "げ",
      "ご",
      "ざ",
      "じ",
      "ず",
      "ぜ",
      "ぞ",
      "だ",
      "ぢ",
      "づ",
      "で",
      "ど",
      "ば",
      "び",
      "ぶ",
      "べ",
      "ぼ",
    ],
    answers: [
      "ga",
      "gi",
      "gu",
      "ge",
      "go",
      "za",
      "ji",
      "zu",
      "ze",
      "zo",
      "da",
      "ji",
      "zu",
      "de",
      "do",
      "ba",
      "bi",
      "bu",
      "be",
      "bo",
    ],
  },
  hiraganaHandakuten: {
    questions: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"],
    answers: ["pa", "pi", "pu", "pe", "po"],
  },
  hiraganaYoon: {
    questions: [
      "きゃ",
      "きゅ",
      "きょ",
      "しゃ",
      "しゅ",
      "しょ",
      "ちゃ",
      "ちゅ",
      "ちょ",
      "にゃ",
      "にゅ",
      "にょ",
      "ひゃ",
      "ひゅ",
      "ひょ",
      "みゃ",
      "みゅ",
      "みょ",
      "りゃ",
      "りゅ",
      "りょ",
      "ぎゃ",
      "ぎゅ",
      "ぎょ",
      "じゃ",
      "じゅ",
      "じょ",
      "びゃ",
      "びゅ",
      "びょ",
      "ぴゃ",
      "ぴゅ",
      "ぴょ",
      // Additional youon combinations
      "でゃ",
      "でゅ",
      "でょ",
      "てゃ",
      "てゅ",
      "てょ",
      "ふゃ",
      "ふゅ",
      "ふょ",
      "ヴゃ",
      "ヴゅ",
      "ヴょ",
    ],
    answers: [
      "kya",
      "kyu",
      "kyo",
      "sha",
      "shu",
      "sho",
      "cha",
      "chu",
      "cho",
      "nya",
      "nyu",
      "nyo",
      "hya",
      "hyu",
      "hyo",
      "mya",
      "myu",
      "myo",
      "rya",
      "ryu",
      "ryo",
      "gya",
      "gyu",
      "gyo",
      "ja",
      "ju",
      "jo",
      "bya",
      "byu",
      "byo",
      "pya",
      "pyu",
      "pyo",
      // Additional youon combinations
      "dya",
      "dyu",
      "dyo",
      "tya",
      "tyu",
      "tyo",
      "fya",
      "fyu",
      "fyo",
      "vya",
      "vyu",
      "vyo",
    ],
  },
  katakanaBasic: {
    questions: [
      "ア",
      "イ",
      "ウ",
      "エ",
      "オ",
      "カ",
      "キ",
      "ク",
      "ケ",
      "コ",
      "サ",
      "シ",
      "ス",
      "セ",
      "ソ",
      "タ",
      "チ",
      "ツ",
      "テ",
      "ト",
      "ナ",
      "ニ",
      "ヌ",
      "ネ",
      "ノ",
      "ハ",
      "ヒ",
      "フ",
      "ヘ",
      "ホ",
      "マ",
      "ミ",
      "ム",
      "メ",
      "モ",
      "ヤ",
      "ユ",
      "ヨ",
      "ラ",
      "リ",
      "ル",
      "レ",
      "ロ",
      "ワ",
      "ヲ",
      "ン",
    ],
    answers: [
      "a",
      "i",
      "u",
      "e",
      "o",
      "ka",
      "ki",
      "ku",
      "ke",
      "ko",
      "sa",
      "shi",
      "su",
      "se",
      "so",
      "ta",
      "chi",
      "tsu",
      "te",
      "to",
      "na",
      "ni",
      "nu",
      "ne",
      "no",
      "ha",
      "hi",
      "fu",
      "he",
      "ho",
      "ma",
      "mi",
      "mu",
      "me",
      "mo",
      "ya",
      "yu",
      "yo",
      "ra",
      "ri",
      "ru",
      "re",
      "ro",
      "wa",
      "wo",
      "n",
    ],
  },
  katakanaTenten: {
    questions: [
      "ガ",
      "ギ",
      "グ",
      "ゲ",
      "ゴ",
      "ザ",
      "ジ",
      "ズ",
      "ゼ",
      "ゾ",
      "ダ",
      "ヂ",
      "ヅ",
      "デ",
      "ド",
      "バ",
      "ビ",
      "ブ",
      "ベ",
      "ボ",
    ],
    answers: [
      "ga",
      "gi",
      "gu",
      "ge",
      "go",
      "za",
      "ji",
      "zu",
      "ze",
      "zo",
      "da",
      "ji",
      "zu",
      "de",
      "do",
      "ba",
      "bi",
      "bu",
      "be",
      "bo",
    ],
  },
  katakanaHandakuten: {
    questions: ["パ", "ピ", "プ", "ペ", "ポ"],
    answers: ["pa", "pi", "pu", "pe", "po"],
  },
  katakanaYoon: {
    questions: [
      "キャ",
      "キュ",
      "キョ",
      "シャ",
      "シュ",
      "ショ",
      "チャ",
      "チュ",
      "チョ",
      "ニャ",
      "ニュ",
      "ニョ",
      "ヒャ",
      "ヒュ",
      "ヒョ",
      "ミャ",
      "ミュ",
      "ミョ",
      "リャ",
      "リュ",
      "リョ",
      "ギャ",
      "ギュ",
      "ギョ",
      "ジャ",
      "ジュ",
      "ジョ",
      "ビャ",
      "ビュ",
      "ビョ",
      "ピャ",
      "ピュ",
      "ピョ",
      // Additional katakana youon combinations
      "デャ",
      "デュ",
      "デョ",
      "テャ",
      "テュ",
      "テョ",
      "ファ",
      "フィ",
      "フェ",
      "フォ",
      "ヴァ",
      "ヴィ",
      "ヴェ",
      "ヴォ",
      "ツァ",
      "ツィ",
      "ツェ",
      "ツォ",
      "ウィ",
      "ウェ",
      "ウォ",
    ],
    answers: [
      "kya",
      "kyu",
      "kyo",
      "sha",
      "shu",
      "sho",
      "cha",
      "chu",
      "cho",
      "nya",
      "nyu",
      "nyo",
      "hya",
      "hyu",
      "hyo",
      "mya",
      "myu",
      "myo",
      "rya",
      "ryu",
      "ryo",
      "gya",
      "gyu",
      "gyo",
      "ja",
      "ju",
      "jo",
      "bya",
      "byu",
      "byo",
      "pya",
      "pyu",
      "pyo",
      // Additional katakana youon combinations
      "dya",
      "dyu",
      "dyo",
      "tya",
      "tyu",
      "tyo",
      "fa",
      "fi",
      "fe",
      "fo",
      "va",
      "vi",
      "ve",
      "vo",
      "tsa",
      "tsi",
      "tse",
      "tso",
      "wi",
      "we",
      "wo",
    ],
  },
  // Data Sokuon (っ/ッ) - Double consonants
  sokuonHiragana: {
    questions: [
      "かっぱ",
      "きっぷ",
      "がっこう",
      "ざっし",
      "てっきょう",
      "にっぽん",
      "びっくり",
      "まっすぐ",
      "やっぱり",
      "らっぱ",
      "さっき",
      "ちっとも",
      "はっきり",
      "みっつ",
      "よっつ",
      "いっしょ",
      "けっして",
      "こっち",
      "そっち",
      "あっち",
      "きっと",
      "ずっと",
      "もっと",
      "ちょっと",
      "しっかり",
    ],
    answers: [
      "kappa",
      "kippu",
      "gakkou",
      "zasshi",
      "tekkyou",
      "nippon",
      "bikkuri",
      "massugu",
      "yappari",
      "rappa",
      "sakki",
      "chittomo",
      "hakkiri",
      "mittsu",
      "yottsu",
      "issho",
      "kesshite",
      "kocchi",
      "socchi",
      "acchi",
      "kitto",
      "zutto",
      "motto",
      "chotto",
      "shikkari",
    ],
  },
  sokuonKatakana: {
    questions: [
      "カップ",
      "キット",
      "グッド",
      "サッカー",
      "セット",
      "トップ",
      "ドッグ",
      "バッグ",
      "ベッド",
      "ホット",
      "マップ",
      "ミット",
      "メッセージ",
      "ロック",
      "ワックス",
      "ショップ",
      "チップ",
      "フィット",
      "ヒット",
      "パック",
      "ピック",
      "プッシュ",
      "ペット",
      "ポップ",
      "アップ",
    ],
    answers: [
      "kappu",
      "kitto",
      "guddo",
      "sakkaa",
      "setto",
      "toppu",
      "doggu",
      "baggu",
      "beddo",
      "hotto",
      "mappu",
      "mitto",
      "messeji",
      "rokku",
      "wakkusu",
      "shoppu",
      "chippu",
      "fitto",
      "hitto",
      "pakku",
      "pikku",
      "pusshu",
      "petto",
      "poppu",
      "appu",
    ],
  },
  // Data Chouon (長音) - Long vowels
  chouonHiragana: {
    questions: [
      "おかあさん",
      "おとうさん",
      "せんせい",
      "がくせい",
      "びいる",
      "こうこう",
      "りゅうがく",
      "しゅうまつ",
      "けいざい",
      "しんかんせん",
      "でんしゃ",
      "ひこうき",
      "たいいく",
      "おんがく",
      "えいが",
      "れいぞうこ",
      "でんわ",
      "きょうしつ",
      "としょかん",
      "びょういん",
    ],
    answers: [
      "okaasan",
      "otousan",
      "sensei",
      "gakusei",
      "biiru",
      "koukou",
      "ryuugaku",
      "shuumatsu",
      "keizai",
      "shinkansen",
      "densha",
      "hikouki",
      "taiiku",
      "ongaku",
      "eiga",
      "reizouko",
      "denwa",
      "kyoushitsu",
      "toshokan",
      "byouin",
    ],
  },
  chouonKatakana: {
    questions: [
      "コーヒー",
      "ケーキ",
      "スープ",
      "チーズ",
      "ビール",
      "ジュース",
      "アイス",
      "メール",
      "インターネット",
      "コンピューター",
      "ゲーム",
      "スポーツ",
      "ニュース",
      "レストラン",
      "ホテル",
      "タクシー",
      "バス",
      "カメラ",
      "テレビ",
      "ラジオ",
    ],
    answers: [
      "koohii",
      "keeki",
      "suupu",
      "chiizu",
      "biiru",
      "juusu",
      "aisu",
      "meeru",
      "intaanetto",
      "konpyuutaa",
      "geemu",
      "supootsu",
      "nyuusu",
      "resutoran",
      "hoteru",
      "takushii",
      "basu",
      "kamera",
      "terebi",
      "rajio",
    ],
  },
};

// Data untuk baris-baris spesifik
const rowData = {
  // Hiragana Rows
  "hiragana-a": {
    questions: ["あ", "い", "う", "え", "お"],
    answers: ["a", "i", "u", "e", "o"],
  },
  "hiragana-ka": {
    questions: ["か", "き", "く", "け", "こ"],
    answers: ["ka", "ki", "ku", "ke", "ko"],
  },
  "hiragana-sa": {
    questions: ["さ", "し", "す", "せ", "そ"],
    answers: ["sa", "shi", "su", "se", "so"],
  },
  "hiragana-ta": {
    questions: ["た", "ち", "つ", "て", "と"],
    answers: ["ta", "chi", "tsu", "te", "to"],
  },
  "hiragana-na": {
    questions: ["な", "に", "ぬ", "ね", "の"],
    answers: ["na", "ni", "nu", "ne", "no"],
  },
  "hiragana-ha": {
    questions: ["は", "ひ", "ふ", "へ", "ほ"],
    answers: ["ha", "hi", "fu", "he", "ho"],
  },
  "hiragana-ma": {
    questions: ["ま", "み", "む", "め", "も"],
    answers: ["ma", "mi", "mu", "me", "mo"],
  },
  "hiragana-ya": {
    questions: ["や", "ゆ", "よ"],
    answers: ["ya", "yu", "yo"],
  },
  "hiragana-ra": {
    questions: ["ら", "り", "る", "れ", "ろ"],
    answers: ["ra", "ri", "ru", "re", "ro"],
  },
  "hiragana-wa": {
    questions: ["わ", "を", "ん"],
    answers: ["wa", "wo", "n"],
  },

  // Katakana Rows
  "katakana-a": {
    questions: ["ア", "イ", "ウ", "エ", "オ"],
    answers: ["a", "i", "u", "e", "o"],
  },
  "katakana-ka": {
    questions: ["カ", "キ", "ク", "ケ", "コ"],
    answers: ["ka", "ki", "ku", "ke", "ko"],
  },
  "katakana-sa": {
    questions: ["サ", "シ", "ス", "セ", "ソ"],
    answers: ["sa", "shi", "su", "se", "so"],
  },
  "katakana-ta": {
    questions: ["タ", "チ", "ツ", "テ", "ト"],
    answers: ["ta", "chi", "tsu", "te", "to"],
  },
  "katakana-na": {
    questions: ["ナ", "ニ", "ヌ", "ネ", "ノ"],
    answers: ["na", "ni", "nu", "ne", "no"],
  },
  "katakana-ha": {
    questions: ["ハ", "ヒ", "フ", "ヘ", "ホ"],
    answers: ["ha", "hi", "fu", "he", "ho"],
  },
  "katakana-ma": {
    questions: ["マ", "ミ", "ム", "メ", "モ"],
    answers: ["ma", "mi", "mu", "me", "mo"],
  },
  "katakana-ya": {
    questions: ["ヤ", "ユ", "ヨ"],
    answers: ["ya", "yu", "yo"],
  },
  "katakana-ra": {
    questions: ["ラ", "リ", "ル", "レ", "ロ"],
    answers: ["ra", "ri", "ru", "re", "ro"],
  },
  "katakana-wa": {
    questions: ["ワ", "ヲ", "ン"],
    answers: ["wa", "wo", "n"],
  },

  // Tenten & Handakuten Rows
  "hiragana-ga": {
    questions: ["が", "ぎ", "ぐ", "げ", "ご"],
    answers: ["ga", "gi", "gu", "ge", "go"],
  },
  "hiragana-za": {
    questions: ["ざ", "じ", "ず", "ぜ", "ぞ"],
    answers: ["za", "ji", "zu", "ze", "zo"],
  },
  "hiragana-da": {
    questions: ["だ", "ぢ", "づ", "で", "ど"],
    answers: ["da", "ji", "zu", "de", "do"],
  },
  "hiragana-ba": {
    questions: ["ば", "び", "ぶ", "べ", "ぼ"],
    answers: ["ba", "bi", "bu", "be", "bo"],
  },
  "hiragana-pa": {
    questions: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"],
    answers: ["pa", "pi", "pu", "pe", "po"],
  },
  "katakana-ga": {
    questions: ["ガ", "ギ", "グ", "ゲ", "ゴ"],
    answers: ["ga", "gi", "gu", "ge", "go"],
  },
  "katakana-za": {
    questions: ["ザ", "ジ", "ズ", "ゼ", "ゾ"],
    answers: ["za", "ji", "zu", "ze", "zo"],
  },
  "katakana-da": {
    questions: ["ダ", "ヂ", "ヅ", "デ", "ド"],
    answers: ["da", "ji", "zu", "de", "do"],
  },
  "katakana-ba": {
    questions: ["バ", "ビ", "ブ", "ベ", "ボ"],
    answers: ["ba", "bi", "bu", "be", "bo"],
  },
  "katakana-pa": {
    questions: ["パ", "ピ", "プ", "ペ", "ポ"],
    answers: ["pa", "pi", "pu", "pe", "po"],
  },
};

// Nama kategori untuk notifikasi
const categoryNames = {
  hiraganaBasic: "Hiragana Dasar",
  hiraganaTenten: "Hiragana Tenten",
  hiraganaHandakuten: "Hiragana Handakuten",
  hiraganaYoon: "Hiragana Yoon",
  katakanaBasic: "Katakana Dasar",
  katakanaTenten: "Katakana Tenten",
  katakanaHandakuten: "Katakana Handakuten",
  katakanaYoon: "Katakana Yoon",
  sokuonHiragana: "Sokuon Hiragana (っ)",
  sokuonKatakana: "Sokuon Katakana (ッ)",
  chouonHiragana: "Chouon Hiragana (長音)",
  chouonKatakana: "Chouon Katakana (長音)",
};

// Nama baris untuk notifikasi
const rowNames = {
  "hiragana-a": "Hiragana Baris A",
  "hiragana-ka": "Hiragana Baris KA",
  "hiragana-sa": "Hiragana Baris SA",
  "hiragana-ta": "Hiragana Baris TA",
  "hiragana-na": "Hiragana Baris NA",
  "hiragana-ha": "Hiragana Baris HA",
  "hiragana-ma": "Hiragana Baris MA",
  "hiragana-ya": "Hiragana Baris YA",
  "hiragana-ra": "Hiragana Baris RA",
  "hiragana-wa": "Hiragana Baris WA",
  "katakana-a": "Katakana Baris A",
  "katakana-ka": "Katakana Baris KA",
  "katakana-sa": "Katakana Baris SA",
  "katakana-ta": "Katakana Baris TA",
  "katakana-na": "Katakana Baris NA",
  "katakana-ha": "Katakana Baris HA",
  "katakana-ma": "Katakana Baris MA",
  "katakana-ya": "Katakana Baris YA",
  "katakana-ra": "Katakana Baris RA",
  "katakana-wa": "Katakana Baris WA",
  "hiragana-ga": "Hiragana Baris GA",
  "hiragana-za": "Hiragana Baris ZA",
  "hiragana-da": "Hiragana Baris DA",
  "hiragana-ba": "Hiragana Baris BA",
  "hiragana-pa": "Hiragana Baris PA",
  "katakana-ga": "Katakana Baris GA",
  "katakana-za": "Katakana Baris ZA",
  "katakana-da": "Katakana Baris DA",
  "katakana-ba": "Katakana Baris BA",
  "katakana-pa": "Katakana Baris PA",
};
